# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'getNameWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import socket
import tkinter as tk
import threading
from functools import partial

from PyQt5.QtGui import QFont

from WhatsappMain import Ui_MainWhatsapp
import time

SERVER_IP = "127.0.0.1"
SERVER_PORT = 1
USERNAME = ""
sent_to = ""

from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, MainWindow,client_sock):
        self.client_sock = client_sock
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(319, 204)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 30, 161, 31))
        self.label.setObjectName("label")
        self.passwordText = QtWidgets.QLineEdit(self.centralwidget)
        self.passwordText.setGeometry(QtCore.QRect(100, 80, 111, 21))
        self.passwordText.setObjectName("passwordText")
        self.nameText = QtWidgets.QLineEdit(self.centralwidget)
        self.nameText.setGeometry(QtCore.QRect(100, 60, 111, 21))
        self.nameText.setObjectName("nameText")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 31, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 61, 21))
        self.label_3.setObjectName("label_3")
        self.registerButton = QtWidgets.QPushButton(self.centralwidget)
        self.registerButton.setGeometry(QtCore.QRect(110, 120, 91, 41))
        self.registerButton.setObjectName("registerButton")
        self.registerButton.setText("Register")
        self.registerButton.setFont(QFont('Arial', 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 319, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Register", "Register"))
        self.label.setText(_translate("MainWindow", "Enter you name and password"))
        self.label_2.setText(_translate("MainWindow", "name:"))
        self.label_3.setText(_translate("MainWindow", "password:"))

        self.registerButton.clicked.connect(self.sendFunction)
        # connection socket

    def sendFunction(self):
        self.client_sock.sendall(f"2@@{self.nameText.text()},{self.passwordText.text()}".encode())
        return_code = self.client_sock.recv(1024).decode()
        print(return_code)
        if return_code == "1":
            self.MainWindow.close()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Username incorrect")
            msg.setText("A user with the same name already exists")
            msg.setIcon(QMessageBox.Critical)
            msg.exec_()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_RegisterWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
